# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dirección',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero_exterior', models.CharField(max_length=50)),
                ('numero_interior', models.CharField(max_length=50)),
                ('manzana', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('código_postal', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('teléfono', models.IntegerField()),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('puesto', models.CharField(max_length=50)),
                ('dirección', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionador_empleados.Dirección')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
